### ISSUE TITLE
CLIENT TO PROXY ERROR

### ISSUE THREAD

**Issue by Su-yj** [zizifn/edgetunnel#61]
使用代理的过程中，报一下错误，但代理还是能正常访问：

```
CLIENT TO PROXY ERROR
TypeError: terminated
    at Fetch.onAborted (C:\snapshot\edgetunnel\node_modules\undici\lib\fetch\index.js:1911:49)
    at Fetch.emit (node:events:537:28)
    at Fetch.terminate (C:\snapshot\edgetunnel\node_modules\undici\lib\fetch\index.js:94:10)
    at Object.onError (C:\snapshot\edgetunnel\node_modules\undici\lib\fetch\index.js:2052:34)
    at Request.onError (C:\snapshot\edgetunnel\node_modules\undici\lib\core\request.js:265:27)
    at errorRequest (C:\snapshot\edgetunnel\node_modules\undici\lib\client.js:1739:13)
    at TLSSocket.onSocketClose (C:\snapshot\edgetunnel\node_modules\undici\lib\client.js:998:5)
    at TLSSocket.emit (node:events:549:35)
    at node:net:747:14
    at TCP.done (node:_tls_wrap:582:7) {
  [cause]: SocketError: other side closed
      at TLSSocket.onSocketEnd (C:\snapshot\edgetunnel\node_modules\undici\lib\client.js:966:22)
      at TLSSocket.emit (node:events:549:35)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
    code: 'UND_ERR_SOCKET',
    socket: {
      localAddress: 'x.x.x.x', // 这里IP我隐藏了
      localPort: 2607,
      remoteAddress: 'x.x.x.x', // 这里IP我隐藏了
      remotePort: 443,
      remoteFamily: 'IPv4',
      timeout: undefined,
      bytesWritten: 17695,
      bytesRead: 519872
    }
  }
}
```

我看了下自己本地是没有这个路径的，估计是项目有些文件引用没有弄好吧？

**Comment by zizifn** [comment]
谢谢测试。这些文件是exe 内部文件。这是pkg打包nodejs的工作原理。。由于目前Realese都是测试code。。所以有很多bug。。已经在改部分bug啦。
